JelajahiNFTs = [
  {
    imageUrl: "assets/NFTs/koleksi/1.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: true,
  },
  {
    imageUrl: "assets/NFTs/koleksi/2.png",
    title: "Pesona Tegallalang",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: false,
  },
  {
    imageUrl: "assets/NFTs/koleksi/3.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: true,
  },
  {
    imageUrl: "assets/NFTs/koleksi/4.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: false,
  },
  {
    imageUrl: "assets/NFTs/koleksi/5.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: true,
  },
  {
    imageUrl: "assets/NFTs/koleksi/6.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: false,
  },
  {
    imageUrl: "assets/NFTs/koleksi/7.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: false,
  },
  {
    imageUrl: "assets/NFTs/koleksi/8.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: true,
  },
];

ExtraJelajahiNFTs = [
  {
    imageUrl: "assets/NFTs/koleksi/9.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: true,
  },
  {
    imageUrl: "assets/NFTs/koleksi/10.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: true,
  },
  {
    imageUrl: "assets/NFTs/koleksi/11.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: true,
  },
  {
    imageUrl: "assets/NFTs/koleksi/12.png",
    title: "Pria Maluku",
    rupiah: "24.100",
    price: "3.99",
    volatility: "32.8%",
    up: true,
  },
];
module.exports = { JelajahiNFTs, ExtraJelajahiNFTs };
