kreatorInfo = [
  {
    imageUrl: "assets/kreator/marchella.png",
    kreator: "Marchella",
    price: "0.99",
    volatility: "32.8%",
    up: true,
  },
  {
    imageUrl: "assets/kreator/hezekiah.png",
    kreator: "Hezekiah",
    price: "0.99",
    volatility: "32.8%",
    up: true,
  },
  {
    imageUrl: "assets/kreator/1.png",
    kreator: "NFTNusa",
    price: "239.56",
    volatility: "12.8%",
    up: false,
  },
  {
    imageUrl: "assets/kreator/2.png",
    kreator: "ARTIFY",
    price: "0.99",
    volatility: "30.8%",
    up: false,
  },
  {
    imageUrl: "assets/kreator/3.png",
    kreator: "CRYPTIX",
    price: "0.99",
    volatility: "32.8%",
    up: true,
  },
  {
    imageUrl: "assets/kreator/4.png",
    kreator: "PixelPop",
    price: "0.99",
    volatility: "42.8%",
    up: true,
  },
  {
    imageUrl: "assets/kreator/5.png",
    kreator: "NeoMint",
    price: "175.26",
    volatility: "18.8%",
    up: true,
  },
  {
    imageUrl: "assets/kreator/6.png",
    kreator: "MetaCraft",
    price: "0.99",
    volatility: "23.8%",
    up: false,
  },
  {
    imageUrl: "assets/kreator/7.png",
    kreator: "ByteBrush",
    price: "0.99",
    volatility: "32.8%",
    up: true,
  },
];
module.exports = { kreatorInfo };
